// "use server"

import ContactPage from "./_components/ContactPage"
// import "./contact.css"

export const metadata: { title: string; description: string } = {
    title: "Create Next App Contact",
    description: "Generated by create next app",
};

const Contact = () => {
    return <ContactPage />
}

export default Contact;