import ServicesPage from "./_components/ServicesPage";
import "./services.css"

export const metadata: { title: string; description: string } = {
    title: "Create Services Page",
    description: "Generated by create next app",
};

const Services = () => {
    return <ServicesPage />
}

export default Services;