import Head from "next/head";
import WorksPage from "./_components/WorksPage";
import { MetaTags } from "@/Hooks/useFetchMetaTags";

const Works = ({ meta }: { meta: MetaTags }) => {
    return (
        <>
            <Head>
                <title>{meta?.title || "Works | Default Title"}</title>
                <meta name="description" content={meta?.description || "Explore our portfolio and past projects."} />
                <meta property="og:title" content={meta?.title || "Works | Default Title"} />
                <meta property="og:description" content={meta?.description || "Explore our portfolio and past projects."} />
                <meta property="og:type" content="website" />
                <meta property="og:url" content="https://wisbato.com/works" />
            </Head>
            <WorksPage />
        </>
    );
};

export async function getServerSideProps() {
    try {
        const res = await fetch("https://backend.wisbato.com/api/metatags?name=works");
        const data = await res.json();

        return {
            props: { meta: data.data[0] },
        };
    } catch (error) {
        console.error("Error fetching metadata:", error);
        return {
            props: { meta: null },
        };
    }
}

export default Works;



// import WorksPage from "./_components/WorksPage";

// export const metadata: { title: string; description: string } = {
//     title: "Create Works Page",
//     description: "Generated by create next app",
// };

// const Works = () => {
//     return <WorksPage />
// }

// export default Works
