// 3 //////////////////////////////

// import WorksPage from './_components/WorksPage';
// import "../globals.css";
// import "./works.css";
// import axios from 'axios';
// import { Work } from '@/Hooks/useFetchData';


// export const metadata = {
//     title: "Wisbato Works",
//     description: "Showcase of Wisbato's creative projects",
// };

// const fetchWorks = async (): Promise<Work[]> => {
//     try {
//         const response = await axios.get('https://backend.wisbato.com/api/works');
//         return response.data.data;
//     } catch (error) {
//         console.error('Error fetching works:', error);
//         return [];
//     }
// };

// const Works = async () => {
//     const works = await fetchWorks();

//     if (works.length === 0) {
//         return <div>No works found</div>;
//     }

//     return <WorksPage works={works} />;
// };

// export default Works;

// 2 //////////////////////////////

// "use server"

// import WorksPage from './_components/WorksPage';
// import "../globals.css";
// import "./works.css";
// import axios from 'axios';
// import { Work } from '@/Hooks/useFetchData';

// export const metadata = {
//     title: "Create Works Page",
//     description: "Generated by create next app",
// };

// const fetchWorks = async (): Promise<Work[]> => {
//     try {
//         const response = await axios.get('https://backend.wisbato.com/api/works');
//         return response.data.data;
//     } catch (error) {
//         console.error('Error fetching works:', error);
//         return [];
//     }
// };

// const Works = async () => {
//     const works = await fetchWorks();

//     return <WorksPage works={works} />;
// };

// export default Works;


// 1 //////////////////////////////

import "../globals.css"
import WorksPage from "./_components/WorksPage";
// import "./works.css"

export const metadata: { title: string; description: string } = {
    title: "Create Works Page",
    description: "Generated by create next app",
};

const Works = () => {
    return <WorksPage />
}

export default Works
