import Head from "next/head";
import Home from "../components/Home/Home";
import "./globals.css"

export const metadata: { title: string; description: string } = {
  title: "Create Next App Home",
  description: "Generated by create next app",
};

export default function HomePage() {
  return (
    <main>
      <Head>
        <title>Home</title>
        <meta name="description" content="metaTags description" />
        <link rel="canonical" href="https://www.wisbato.com" />
      </Head>

      <Home />
    </main>
  );
}
