import TeamPage from "./_components/TeamPage";
// import './team.css'

export const metadata: { title: string; description: string } = {
    title: "Create Works Team",
    description: "Generated by create next app",
};

const Team = () => {
    return <TeamPage />
}

export default Team
