// "use server"

import AboutPage from "./AboutPage"
import "../globals.css"
import "./about.css"

export const metadata: { title: string; description: string } = {
    title: "Create Next App About",
    description: "Generated by create next app",
};

const About = () => {
    return <AboutPage />
}

export default About