// "use server"

import BlogsPage from './_components/BlogsPage'
import "../globals.css"
// import "./blogs.css"

export const metadata: { title: string; description: string } = {
    title: "Create Next App Blogs",
    description: "Generated by create next app",
};

const Blogs = () => {
    
    return <BlogsPage />
}

export default Blogs
