import WorksPage from './_components/WorksPage'
import "../globals.css"
import "./works.css"

export const metadata: { title: string; description: string } = {
    title: "Create Works Page",
    description: "Generated by create next app",
};

const Works = () => {
    return <WorksPage />
}

export default Works
